### ISSUE TITLE
Invalid message

### ISSUE THREAD

**Issue by wyounglee** [dimircea/WebRTC#1]
When I connect to server using IP and port number,
I get a message "Upgrade required" from Chrome browser.

What is this message?

**Comment by vishvandanak** [comment]
Same here.. were you able to solve it?

**Comment by vishvandanak** [comment]
same here...were you able to solve it?

**Comment by nanu95** [comment]
same here.. were you able to resolve?

**Comment by dimircea** [comment]
It most probably means that you are using HTTP instead of HTTPS. HTTP does not works with WebRTC starting with January of February this year.
