### ISSUE TITLE
Ajutor!

### ISSUE THREAD

**Issue by gabipintea** [dimircea/WebRTC#4]
Salut, Mircea! Imi cer scuze ca te deranjez. Ma numesc Gabriel si sunt student in Bucuresti la Universitate pe sectia de informatica. Am mare nevoie sa realizez o pagina simpla in care sa pot face un videochat (skype-like). Din nefericire, nu am toate cunostiintele necesare pentru a face asta, nefiind specialist in programare web. Ma poti indruma putin zicandu-mi macar cum pot folosi materialele tale? Le-am urcat pe un server personal si de aici m-am blocat. Iti raman profund recunoscator!

O zi placuta!

**Comment by dimircea** [comment]
Salutare Gabriel,

O sa ai nevoie de Node.js si un server unde sa poti sa faci configurarile necesare pentru a rula aplicatia. 
Aici am publicat un tutorial care explica pasii necesari pentru a putea rula aplicatia: http://web-engineering.info/node/57

Este posibil (dar putin probabil) ca tutorialul sa fie putin "out of date", insa nu cred ca sunt prea multe lucruri care s-au schimbat intre timp in WebRTC asa dramatic incat sa impiedice rularea aplicatiei asa cum e descris in tutorial.

Numai bine si spor la Facultate,
Mircea

**Comment by gabipintea** [comment]
Salut,

Intrebarea este veche dar apreciez foarte mult raspunsul 👍🏻  Proiectul de la vremea aceea inca este in desfasurare, deci sigur gasesc informatii useful in tutorial. Faceam curat si reconfiguram contul si am zis sa inchid toate problemele vechi.

Multumesc si mult spor,
Gabriel
