### ISSUE TITLE
Nodejs with webrtc

### ISSUE THREAD

**Issue by deepdil-enfin** [dimircea/WebRTC#7]
Hi,

I like to listen my nodejs port in 3000 port and  websocket in 3001 port. How can i implement it?

**Comment by dimircea** [comment]
The way on which this example is implemented, you have to use one port for both (so either 3000 or 3001). You must also open the selected port on your server firewall. Use firewalld or iptables on a Linux server. 

E.g., to use the port 3001 do the following:

1. edit the webrtc.js file and on line 10 do the following change:

   ` wssHost: 'wss://yourdomainname.xxx:3001'`

    where `yourdomainname.xxx` must be changed with your real domain name.

2. edit the 'server.js' file, and on line 24, replace 443 with 3001 as follows:

   `sslSrv = https.createServer(options, app).listen(3001);`

3. start the nodejs server (execute  `node server.js ` from the application folder)
4. open a web browser that supports webrtc (e.g., Chrome, Firefox, etc) and use the url:
   `https://yourdomainname.xxx:3001`

It is also possible to use different ports for the nodejs HTTP(S) server and WSS, but first try out this and make sure that it works with the default implementation, then come back and I will explain you how to do it with different ports.

**Comment by deepdil-enfin** [comment]
@dimircea  ya its working ok, whats next?

**Comment by dimircea** [comment]
There are a few ways to use different ports (so one for the HTTP(S) server and another one for WSS). With the current used WSS library, the simplest one is to create a second HTTP(S) server that listen on a diferent port and provide it as parameter for the WSS. So, to use the port 3000 for the NodeJS server that delivers your static files and so on, use:

`sslSrv = https.createServer(options, app).listen(3000);  // server.js line 24`

Further, create another HTTP(S) server for the WSS (on port 3001), add the following line:

`var sslSrvForWss = https.createServer(options).listen(3001);`
    then
`wss = new WebSocketServer({server: sslSrvForWss});  // notice the server parameter value!`
    instead of
`wss = new WebSocketServer({server: sslSrv}); // notice the server parameter value!` 

Then on the webrtc.js file, remember to use the correct port, which is now 3001.
`wssHost: 'wss://yourdomainname.xxx:3001'`

And to answer your last question...next you do what you like...extend the application example to fit your needs.

**Comment by dimircea** [comment]
I close now this issue...since this is not a issue/problem with the example project itself.
